<?php

namespace Acme\BnqaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MisprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MisprintRepository extends EntityRepository
{
}
