<?php

namespace Acme\BnqaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserFollowingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFollowingRepository extends EntityRepository
{
  public function findPersonalArchivesByUser(User $user)
  {
    $results = $this->getEntityManager()->
      createQuery('SELECT f,u FROM AcmeBnqaBundle:UserFollowing f JOIN f.followingUser u WHERE f.user = :user')
      ->setParameter('user',$user)
      ->setMaxResults(10)
      ->getResult();

    return $results;
  }
}
